name: CI
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run-script build-prod  # package.json -> "scripts"
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@master # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
